= ホームネットワーク構築

== iptables

* ようやく動くようになった？
** とりあえず内部ネットワークから名前解決できるようになった。
* 今ってどこにNSが設定されてるんだろう
** Ubuntuの内部DNSにくるまれててわからない
*** `/etc/resolvconf/resolv.conf.d/base` に書き込んで `resolvconf -u` すると更新できるらしい
**** 1.1.1.1が登録されたままになってる
**** `resolveconf -u` しても消えない
***** `/etc/systemd/resolved.conf` に直にDNS書き込んでた

== dnsmasq

* iptablesが一段落したらDNSがきちんと解決できてないことがわかった
** 192.168.234.121に問い合わせても帰ってこない
** 1.1.1.1に問い合わせると帰ってくる
* 現在のUbuntuではdnsmasqじゃなくてsystemd-resolvになってる
** それに従ってローカルでDNSする専用の動作に変わってるっぽい
* Systemdにいろいろさせるほうが良さそう？
** [systemd-networkd に仮想 bridge を作成させる方法 - memo](https://u7fa9.org/memo/HEAD/archives/2015-07/2015-07-08.rst)
* そもそもdnsmasq立ち上がってない
** top -p `pgrep -d ',' "java|tomcat|redis|mysql|mongo"`
** dnsmasq.serviceがないので多分マスカレードできてない
** `dhclient -r eth0` で開放できない
*** いま持ってるDNSでとってきたIPは一体いつどうやってとったんだ？
**** 単純にLeaseしてIPが無くなっただけだった
** つなぎ直すとDNSでIpが振られた
*** 一体だれがIPを振っているのか…
**** DHCPD.confだ！思い出した！
**** そうか！dhcpcdでマスカレードすればいいのか！
***** 多分だめ
***** dhcpcd=DHCPを振る、dnsmasq=DHCPを振る＋"ファイアウォールの対内側にDNSを提供できる。"[Dnsmasq - Wikipedia](https://ja.wikipedia.org/wiki/Dnsmasq)
*** もはやBINDをDockerで上げてDHCPと一緒に放り込むほうがいいのでは
**** 最終的にBIND立てることが視野に入ってるのでBIND立てる
**** Netplanで固定IP振ることは変わらないけど、dhcpcdは止める、iptablesはそのまま
**** Docker内部は全く別のネットワークなので、注意が必要
***** 外部<-->BIND<-->？
**** そもそもサブドメインの運用ってどうするんだ？
**** いろいろわからないー
* とりあえずDNSは挫折、PholcidaeはDHCPでとってきたやつ、Sparassidaeは1.1.1.1を直打ち

* 現在のTarget一覧
** systemctl list-units --type target

= ZFSのディスクアレイからエラーが帰ってくる

* HDDが逝ったかもしれん
* `/dev/disk/by-path/` で `ls -a` するとマップ先がわかる
* smarttestにも1台引っかかる
* バックアップしようとしたらデータがない！？
** やばい
** マウントされてなかっただけだった、マウントしたらちゃんとあった
*** すでにルートに存在していたディレクトリはなんだったのか…

---
    [ 20:41:44 04/12/2018 madpepper ] ~ 
$ sudo zpool status -v
[sudo] password for madpepper: 
  pool: warehouse
 state: DEGRADED
status: One or more devices could not be used because the label is missing or
	invalid.  Sufficient replicas exist for the pool to continue
	functioning in a degraded state.
action: Replace the device using 'zpool replace'.
   see: http://zfsonlinux.org/msg/ZFS-8000-4J
  scan: resilvered 124M in 0h2m with 0 errors on Sat Dec  1 02:27:07 2018
config:

	NAME                                                STATE     READ WRITE CKSUM
	warehouse                                           DEGRADED     0     0     0
	  raidz2-0                                          DEGRADED     0     0     0
	    9961331460964934652                             UNAVAIL      0     0     0  was /dev/disk/by-id/ata-ST3000DM001-1CH166_Z1F0VJQP-part1
	    ata-ST3000DM001-1CH166_Z1F13Q5Q-part1           ONLINE       0     0     0
	    ata-ST3000DM001-1ER166_Z502DLMK-part1           ONLINE       0     0     0
	    ata-WDC_WD40EZRZ-00GXCB0_WD-WCC7K6AC39D5-part1  ONLINE       0     0     0
	    ata-ST3000DM008-2DM166_Z5032B21-part1           ONLINE       0     0     0
	    ata-ST3000DM008-2DM166_Z503JQGW-part1           ONLINE       0     0     0
	    ata-ST3000DM008-2DM166_Z504NYEH-part1           ONLINE       0     0     0
	    ata-ST3000DM008-2DM166_Z504P2FN-part1           ONLINE       0     0     0

errors: No known data errors
---


= その他

* VSCodeのSSH FSめっちゃ便利
** サーバー上のファイルをいつものエディタで変更できる
** コマンド叩くのとはシームレスにはならないかも
** vimのほうがきれいにハイライトできる？
** コード編集はVSCodeのほうがいいだろうけど、ちょっとした編集はVimのほうがよさそう
* zcat、そんなもんあるのか
** gzの中身をテキスト表示できる
